---
# tasks file for httpd
- name: Installing httpd 
  yum: 
    name: httpd 
    state: latest
- name: Copying file 
  copy: 
    src: index.html
    dest: "{{ dest }}/index.html" 
    mode: 0755
  notify: restart httpd 

